//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticSolutionFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialStatement
    {
        public int FinancialStatementId { get; set; }
        public int Year { get; set; }
        public int 자산 { get; set; }
        public int 부채 { get; set; }
        public int 자본 { get; set; }
        public int 매출액 { get; set; }
        public int 매출원가 { get; set; }
        public int 매출총이익 { get; set; }
        public int 판매비와관리비 { get; set; }
        public int 영업이익 { get; set; }
        public int 영업외손익 { get; set; }
        public int 당기순이익 { get; set; }
    }
}
