//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticSolutionFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialStatement
    {
        public int FinancialStatementId { get; set; }
        public int Year { get; set; }
        public int 자산 { get; set; }
        public int 부채 { get; set; }
        public int 자본 { get; set; }
        public int 매출액 { get; set; }
        public int 매출원가 { get; set; }
        public int 매출총이익 { get; set; }
        public int 판매비와관리비 { get; set; }
        public int 영업이익 { get; set; }
        public int 영업외손익 { get; set; }
        public int 당기순이익 { get; set; }
    }
}
