//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticSolutionFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultOfAnalysi
    {
        public int ResultOfAnalysisId { get; set; }
        public System.DateTime AnalizedAt { get; set; }
        public int StationId { get; set; }
        public int ScoreOfWomenRatio { get; set; }
        public int ScoreOfCompetitorStore { get; set; }
        public int ScoreOfStoreSpace { get; set; }
        public int ScoreOfBranchNumber { get; set; }
    
        public virtual Station Station { get; set; }
    }
}
